[TC2-1218] kazakhstan api doc
credy/api-v3-docs pull request #26
Opened 2022-10-31 15:42 UTC by kalmerkaurson

2022-10-31 18:27 UTC, Nuffic requested changes

2022-10-31 18:27 UTC, Nuffic commented on affiliates/kazakhstan.swagger.json
> +    "description" : "# Introduction \n\nCredy is a company that specializes on the quality lead generation. \\\nThis document further describes how to integrate API to send leads to Credy.\\\nIf you
credy.ge?

2022-10-31 18:27 UTC, Nuffic commented on affiliates/kazakhstan.swagger.json
> +        "description" : "To get response error messages in kazakhstan, header’s value must be set to according ISO code. Ex: `kz` or `kz-KZ`.",
its ru-KZ

2022-10-31 18:27 UTC, Nuffic commented on affiliates/kazakhstan.swagger.json
> +        "example" : "kz-KZ"
its ru-KZ

2022-10-31 18:27 UTC, Nuffic commented on affiliates/kazakhstan.swagger.json
> +          "description" : "To get response error messages in kazakhstan, header’s value must be set to according ISO code. Ex: `kz` or `kz-KZ`.",
its ru-KZ

2022-10-31 18:27 UTC, Nuffic commented on affiliates/kazakhstan.swagger.json
> +          "example" : "kz-KZ"
its ru-KZ

2022-10-31 18:27 UTC, Nuffic commented on affiliates/kazakhstan.swagger.json
> +        "description" : "To get response error messages in Indonesian, header’s value must be set to according ISO code. Ex: `ka`.",
indonesian?

2022-11-01 08:53 UTC, kalmerkaurson commented on affiliates/kazakhstan.swagger.json
> +    "description" : "# Introduction \n\nCredy is a company that specializes on the quality lead generation. \\\nThis document further describes how to integrate API to send leads to Credy.\\\nIf you
fixed

2022-11-01 08:53 UTC, kalmerkaurson commented on affiliates/kazakhstan.swagger.json
> +        "description" : "To get response error messages in kazakhstan, header’s value must be set to according ISO code. Ex: `kz` or `kz-KZ`.",
fixed

2022-11-01 08:53 UTC, kalmerkaurson commented on affiliates/kazakhstan.swagger.json
> +        "example" : "kz-KZ"
fixed

2022-11-01 08:53 UTC, kalmerkaurson commented on affiliates/kazakhstan.swagger.json
> +          "description" : "To get response error messages in kazakhstan, header’s value must be set to according ISO code. Ex: `kz` or `kz-KZ`.",
fixed

2022-11-01 08:53 UTC, kalmerkaurson commented on affiliates/kazakhstan.swagger.json
> +          "example" : "kz-KZ"
fixed

2022-11-01 08:53 UTC, kalmerkaurson commented on affiliates/kazakhstan.swagger.json
> +        "description" : "To get response error messages in Indonesian, header’s value must be set to according ISO code. Ex: `ka`.",
fixed

2022-11-01 12:08 UTC, merged