Spanish api docs
credy/api-v3-docs pull request #6
Opened 2018-07-17 10:56 UTC by baskof147

2018-07-18 09:47 UTC, Nuffic requested changes

2018-07-18 09:47 UTC, Nuffic commented on affiliates/Spain.md
> +| personal_id                     | Required <br /> must be valid PESEL                                                                                                                 | PESEL
PESEL = tidak valid

2018-07-20 09:26 UTC, baskof147 commented on affiliates/Spain.md
> +| personal_id                     | Required <br /> must be valid PESEL                                                                                                                 | PESEL
fixed

2018-07-20 11:33 UTC, mikk150 requested changes

2018-07-20 11:33 UTC, mikk150 commented on affiliates/Spain.md
> +| nationality                     | Optional <br /> string (max 255), must match regex: `/^[a-záéèíñóúüç[:space:]-\']+$/ui`                                                       | Last name of the cu
nationality is last name of the customer?

2018-07-20 11:33 UTC, mikk150 commented on affiliates/Spain.md
> +| bank_account                    | Optional <br /> must be valid IBAN, must match regex: `/(ES|PT).*/`                                                                                 | Bank account
for some reason it renders incoreclty

2018-07-20 11:51 UTC, baskof147 commented on affiliates/Spain.md
> +| nationality                     | Optional <br /> string (max 255), must match regex: `/^[a-záéèíñóúüç[:space:]-\']+$/ui`                                                       | Last name of the cu
fixed

2018-07-20 11:51 UTC, baskof147 commented on affiliates/Spain.md
> +| bank_account                    | Optional <br /> must be valid IBAN, must match regex: `/(ES|PT).*/`                                                                                 | Bank account
fixed

2018-12-17 14:05 UTC, mikk150 approved these changes

2019-11-06 10:55 UTC, Nuffic commented
Pull request not actual, we are already moving to swagger docs.

2019-11-06 10:55 UTC, closed without merging